# Site Settings
title: Drummond B. Fielding
email: dbf233@nyu.edu
description: Computational Astrophysicist | Assistant Professor at New York University
baseurl: ""
url: "https://dfielding14.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CLAUDE.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"