# Minimal Jekyll Configuration for Drummond B. Fielding

# Site Settings
title: Drummond B. Fielding
email: dbf233@nyu.edu
description: Computational Astrophysicist | Assistant Professor at New York University
baseurl: ""
url: "https://dfielding14.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE
  - package.json
  - package-lock.json
  - node_modules
  - _config_new.yml
  - IMPLEMENTATION_PLAN.md
  - CLAUDE.md
  - markdown_generator/
  - _drafts/
  - _site/
  - .sass-cache/
  - .jekyll-metadata

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Plugins (minimal set)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"